using System.Collections.Generic;
using UnityEngine;

namespace Kitchen.AI
{
    public enum TaskType
    {
        FETCH,          // Go to ContainerCounter, get ingredient, deliver to processing facility
        FETCH_PLATE,    // Go to PlatesCounter, get plate, place on ClearCounter
        PROCESS,        // Go to CuttingCounter/StoveCounter, process item, take result
        ADD_TO_PLATE,   // Pick up ingredient, go to ClearCounter with plate, add to plate
        SERVE,          // Pick up completed plate, go to DeliveryCounter, deliver
        TRASH           // Pick up burned/waste item, deliver to TrashCounter
    }

    /// <summary>
    /// A candidate task for an AI chef to execute.
    /// Tasks are generated by KitchenTaskGenerator and assigned by KitchenAIManager.
    /// </summary>
    [System.Serializable]
    public class KitchenTask
    {
        public int id;
        public TaskType type;
        public string label;

        // New planner-facing description. The legacy TaskType remains the
        // execution compatibility layer for AIChefController.
        public KitchenActionType actionType = KitchenActionType.None;
        public ulong objectAId;
        public ulong objectBId;
        public bool targetIsGround;
        public Vector3 groundPosition;
        public List<int> dependencyTaskIds = new();
        public List<KitchenConditionSpec> preconditions = new();
        public List<KitchenConditionSpec> postconditions = new();
        public int retryCount;
        public int maxRetryCount = 3;

        // Which order this task belongs to (0 if open prep)
        public int orderId;

        // The target facility (for FETCH, PROCESS, ASSEMBLE, SERVE)
        public BaseCounter targetFacility;

        // Destination facility (for CARRY tasks)
        public BaseCounter destFacility;

        // The item to operate on
        public KitchenObj targetItem;
        public KitchenObjEnum itemType;
        public KitchenObjEnum outputType;

        // Step info
        public string stepId;

        // Assignment
        public int assignedAgentId;
        public string status = "pending"; // pending, assigned, executing, completed

        // How long the working phase takes
        public float duration = 1.0f;

        public bool isCleanupTask;

        // Items reserved by this task
        public System.Collections.Generic.List<int> reservedItemIds = new();

        private static int _nextId = 1;

        public static KitchenTask Create(TaskType type, string label)
        {
            return new KitchenTask
            {
                id = _nextId++,
                type = type,
                label = label,
                actionType = type switch
                {
                    TaskType.FETCH => KitchenActionType.SpawnFromStorage,
                    TaskType.PROCESS => KitchenActionType.Process,
                    TaskType.FETCH_PLATE => KitchenActionType.Transfer,
                    TaskType.ADD_TO_PLATE => KitchenActionType.AddToPlate,
                    TaskType.SERVE => KitchenActionType.Serve,
                    TaskType.TRASH => KitchenActionType.Trash,
                    _ => KitchenActionType.None,
                },
            };
        }
    }
}
