using UnityEngine;

namespace Kitchen.AI
{
    public enum TaskType
    {
        FETCH,          // Go to ContainerCounter, get ingredient, deliver to processing facility
        FETCH_PLATE,    // Go to PlatesCounter, get plate, place on ClearCounter
        PROCESS,        // Go to CuttingCounter/StoveCounter, process item, take result
        ADD_TO_PLATE,   // Pick up ingredient, go to ClearCounter with plate, add to plate
        SERVE,          // Pick up completed plate, go to DeliveryCounter, deliver
        TRASH           // Pick up burned/waste item, deliver to TrashCounter
    }

    /// <summary>
    /// Detailed score breakdown for a (agent, task) pair.
    /// Mirrors the HTML simulation's scoring dimensions.
    /// </summary>
    [System.Serializable]
    public class ScoreDetail
    {
        public float distance;
        public float facilityWait;
        public float orderUrgency;
        public float unlockValue;
        public float roleBonus;
        public float stockBase;
        public float freshPickBonus;
        public float stalePickPenalty;
        public float total;

        public override string ToString()
        {
            return $"dist={distance:F2} wait={facilityWait:F2} urgency={orderUrgency:F2} " +
                   $"unlock={unlockValue:F2} role={roleBonus:F2} stock={stockBase:F2} " +
                   $"fresh={freshPickBonus:F2} stale={stalePickPenalty:F2} => TOTAL={total:F2}";
        }
    }

    /// <summary>
    /// A candidate task for an AI chef to execute.
    /// Tasks are generated by KitchenTaskGenerator and assigned by KitchenAIManager.
    /// </summary>
    [System.Serializable]
    public class KitchenTask
    {
        public int id;
        public TaskType type;
        public string label;

        // Which order this task belongs to (0 if open prep)
        public int orderId;

        // The target facility (for FETCH, PROCESS, ASSEMBLE, SERVE)
        public BaseCounter targetFacility;

        // Destination facility (for CARRY tasks)
        public BaseCounter destFacility;

        // The item to operate on
        public KitchenObj targetItem;
        public KitchenObjEnum itemType;
        public KitchenObjEnum outputType;

        // Step info
        public string stepId;

        // Scoring
        public float score = float.MinValue;
        public ScoreDetail scoreDetail;

        // Assignment
        public int assignedAgentId;
        public string status = "pending"; // pending, assigned, executing, completed

        // How long the working phase takes
        public float duration = 1.0f;

        // Is this an open prep (stock) task, not bound to any order?
        public bool isStockTask;

        // Items reserved by this task
        public System.Collections.Generic.List<int> reservedItemIds = new();

        private static int _nextId = 1;

        public static KitchenTask Create(TaskType type, string label)
        {
            return new KitchenTask
            {
                id = _nextId++,
                type = type,
                label = label,
            };
        }
    }
}
